### PR TITLE
Fixed issue: integer numbers could not be parsed as float

### PR DESCRIPTION
**Pull request by andreaferretti**
I added the line

```nim
    of yTypeInteger:
      discard parseBiggestFloat(item.scalarContent, result)
```

to the function `constructObject` for floats. The reason is that integer numbers are valid floats, but were not parsed as such (i.e., a number such as `34` where a float was expected was rejected)

### CODE REVIEW

**Comment by flyx** [comment]
Interestingly, http://yaml.org/type/float.html requires the decimal point unless for `0`. However, even its regexes contradict it because they do not allow for `0`.

Thankfully, that seems to have been fixed in the [1.2 spec](http://www.yaml.org/spec/1.2/spec.html#id2804092), so I can merge this.

I suspect you want a bugfix release?

**Comment by andreaferretti** [comment]
Yeah, that would be useful :-)

**Comment by flyx** [comment]
There you are.

**Comment by andreaferretti** [comment]
Thank you a lot!

**Pull request merged**
