### PR TITLE
fix compilation by complying with latest nim's fix for reraise. not sure it's optimal, but at least compiles.

### PR DESCRIPTION
**Pull request by kobi2187**

### CODE REVIEW

**Comment by kobi2187** [comment]
...

**Comment by flyx** [comment]
Why did you close it?

**Comment by kobi2187** [comment]
won't it apply the 2 previous commits? sorry i'm such a newbie with git stuff

**Comment by kobi2187** [comment]
Anyway, it's really easy to fix now. Just add Exception (to the raises list) wherever it tells you there's a problem. in vscode, you can jump to the position with alt+click if i remember correctly.

**Comment by flyx** [comment]
You need to update upstream in your fork.

Basically, assuming you are inside the local copy of your fork, do

    git remote add upstream git@github.com:flyx/NimYAML.git
    git fetch upstream
    git rebase upstream/devel # or merge if rebase doesn't work
    git push origin devel # push upstream changes to your fork at GitHub

I see you are creating your pull request from your `devel` branch. This is a bad idea. Basic PR creation is:

 * Get your `devel` to be up to date with `upstream/devel` (see above)
 * branch from your `devel` and put your *new* commits in that branch
 * push your branch to your fork at GitHub and create a PR from it.

Ensuring that your and my `devel` are the same avoids having duplicate commits in the PR, like what happened here.

**Pull request closed without merging**
